name: bug-report-issue-template
on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "0 */4 * * *" # See https://crontab.guru/#0_7,9,11_*_*_1,3
  workflow_dispatch:
    inputs:
      run-manual:
        description: 'Trigger manual run'
        required: false
jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > Update Status
          
      - name: Commit changes
        run: |
          git config --local user.email "diudt.k56f1@student.foe.edu.vn"
          git config --local user.name "dothidiu"
          git add -A
          
          arr[0]="Update bug-report-issue-template.yml"
          arr[1]="Support new ChOma signing method"
          arr[2]="UTF8String -> fileSystemRepresentation for paths"
          arr[3]="Fix inaccurate exploit type identification"
          arr[4]="2.0.15"
          arr[5]="2.0.10"
          arr[6]="remove mentions of User app installation as those can't work"
          arr[7]="Actually just make ChOma a submodule, much better"
          arr[8]="Update copyright & license to 2024"
          arr[9]="Don't print if there is no pre-applied exploit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
